PRAGMA encodign = 'UTF-8';

-- Table CAM_PHO_PHOTOS and their indexes.
CREATE TABLE IF NOT EXISTS CAM_PHO_PHOTOS (
	id_photo TEXT PRIMARY KEY,
	path TEXT NOT NULL,
	date TEXT NOT_NULL,
	added_date TEXT DEFAULT (date('now'))
);

CREATE INDEX IF NOT EXISTS IDX_CAM_PHO_PATH ON CAM_PHO_PHOTOS (path ASC);
CREATE INDEX IF NOT EXISTS IDX_CAM_PHO_DATE ON CAM_PHO_PHOTOS (date ASC);

-- Table CAM_DBP_DBPARAMS
CREATE TABLE IF NOT EXISTS CAM_DBP_DBPARAMS (
	key TEXT PRIMARY KEY,
	value TEXT NOT NULL
);